# Generated by Django 2.1.2 on 2019-04-04 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='created_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hub',
            name='game_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hub',
            name='modified_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hubscore',
            name='created_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hubscore',
            name='modified_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invites',
            name='created_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invites',
            name='modified_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='created_dttm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='modified_dttm',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
