# Generated by Django 2.1.2 on 2019-04-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190404_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hub',
            old_name='hub_finish_dttm',
            new_name='finish_dttm',
        ),
        migrations.RenameField(
            model_name='hub',
            old_name='hub_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hub',
            old_name='hub_start_dttm',
            new_name='start_dttm',
        ),
        migrations.AddField(
            model_name='hub',
            name='faceit_hub_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
